version: '3.3'
services:
  hotel_reviewer:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ELASTIC_INDEX=hotel_index
      - SUBSCRIPTION_API_KEY=5bf21c030f55483a9aab8659dc9cee51
      - DEBUG=@bool false
      - TESTING=@bool false
    volumes:
      - ./app:/app
    entrypoint: ''
    image: hotel_reviewer
    links:
      - elasticsearch
      - redis
    stdin_open: true
    tty: true

  redis:
    image: redis:4.0

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - cluster.name=hotel_reviewer-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
